// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHllDJ3DE2vI71xy4x47YGUJfbcjQUBy4',
    appId: '1:418428525780:web:085e6398df40840eca2f41',
    messagingSenderId: '418428525780',
    projectId: 'resq-mvp',
    authDomain: 'resq-mvp.firebaseapp.com',
    storageBucket: 'resq-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvi7UspYGfCJMC2D1LhfEDOBauIKkJNuE',
    appId: '1:418428525780:android:8e7f7930c8d5b678ca2f41',
    messagingSenderId: '418428525780',
    projectId: 'resq-mvp',
    storageBucket: 'resq-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzvYyOECyp6d1a7pCOTFfEjprv8umxrOk',
    appId: '1:418428525780:ios:a027c6bb83205112ca2f41',
    messagingSenderId: '418428525780',
    projectId: 'resq-mvp',
    storageBucket: 'resq-mvp.firebasestorage.app',
    iosClientId: '418428525780-8v57kq87jugcgjopavdb2skjmg7qf435.apps.googleusercontent.com',
    iosBundleId: 'com.example.resqAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzvYyOECyp6d1a7pCOTFfEjprv8umxrOk',
    appId: '1:418428525780:ios:a027c6bb83205112ca2f41',
    messagingSenderId: '418428525780',
    projectId: 'resq-mvp',
    storageBucket: 'resq-mvp.firebasestorage.app',
    iosClientId: '418428525780-8v57kq87jugcgjopavdb2skjmg7qf435.apps.googleusercontent.com',
    iosBundleId: 'com.example.resqAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHllDJ3DE2vI71xy4x47YGUJfbcjQUBy4',
    appId: '1:418428525780:web:6b45b99fc1b041c3ca2f41',
    messagingSenderId: '418428525780',
    projectId: 'resq-mvp',
    authDomain: 'resq-mvp.firebaseapp.com',
    storageBucket: 'resq-mvp.firebasestorage.app',
  );
}
